language: python

install:
  - pip install .

before_script:
  - git clone https://github.com/xumi1993/seispy-test test

jobs:
  include:
    - stage: test
      python: "3.7"
      script: bash test/run.sh

    - stage: test
      python: "3.8"
      script: bash test/run.sh

    - stage: test
      python: "3.9"
      script: bash test/run.sh

    - stage: doc
      script: bash -c "$(curl -fsSL https://git.nju.edu.cn/xumi1993/source/-/raw/master/trigger.sh)"

    - stage: deploy
      provide: pypi
      username: "__token__"
      password: "pypi-AgEIcHlwaS5vcmcCJGYyMTBiN2I0LTdmMjAtNGU2MS04YTYzLWU3MTUwNjFhNDliZQACPnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJweXRob24tc2Vpc3B5Il19LCAidmVyc2lvbiI6IDF9AAAGIOMKxAfuV86HTU-hsz2k9Xi-G0-C_wW0hhe3SCuUVcDn"
      on:
        python: 3.8
        branch: master
