language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install obspy pandas pytz netCDF4 pyerf
  - pip install .
  - git clone https://github.com/xumi1993/seispy-test test

jobs:
  include:
    - stage: test
      script:
        - cd test/testcase01
        - python testcase01.py
        - cd ../testcase02
        - python testcase02.py
    
    - stage: doc
      script: bash -c "$(curl -fsSL https://git.nju.edu.cn/xumi1993/source/-/raw/master/trigger.sh)"

